name       : SDL_ttf
version    : 2.0.11
release    : 1
source     :
    - https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.tar.gz : 724cd895ecf4da319a3ef164892b72078bd92632a5d812111261cde248ebcdb7
license    : LGPL-2.1 # CHECK ME
summary    : library which allows you to use TrueType fonts in your SDL applications 
description: |
    library which allows you to use TrueType fonts in your SDL applications
builddeps  : 
       - pkgconfig(sdl) 
       - pkgconfig(freetype2)
setup      : |
        %configure --disable-static
build      : |
    %make
install    : |
    %make_install
